### ISSUE TITLE
How to comment only with summary

### ISSUE THREAD

**Issue by skhalymon** [fluxninja/openai-pr-reviewer#105]
Firstly, thanks for the great thing!

Currently, it's really noisy https://github.com/ALLATRA-IT/ephyr/pull/348 and most of the comments that GPT not understand the context. I want to decrease such number of notifications and leave only a summary comment. How it's possible to achieve?

**Comment by skhalymon** [comment]
Oh, I see that #103 PR should solve this issue

**Comment by harjotgill** [comment]
Yes, we will add a flag soon. @karansohi is working on it.

**Comment by harjotgill** [comment]
Added in #114
