### ISSUE TITLE
Feature Request: code improve suggestion

### ISSUE THREAD

**Issue by ChoKhoOu** [fluxninja/openai-pr-reviewer#124]
Like this #111, I gave an example in there.

When providing code suggestions, developers can directly choose to commit the suggestion

**Comment by harjotgill** [comment]
I struggled to make it work last night, see #123. 
Do you want to give this a shot? :)

**Comment by harjotgill** [comment]
@ChoKhoOu Do check my latest changes. I changed diff format and OpenAI seems to be behaving a little bit better.

**Comment by harjotgill** [comment]
The recent comments by OpenAI seem to be aligning well with the code now. I will ask it to use suggestion code blocks next. Finger crossed. :)

https://github.com/fluxninja/aperture/pull/1699

**Comment by harjotgill** [comment]
Works 60%-70% of the time with new changes and I am out of further ideas today,

**Comment by ChoKhoOu** [comment]
Cool!!!  forked this project yesterday and tried a lot of prompts but they were not satisfactory, I didn't think you had done it!

**Comment by ChoKhoOu** [comment]
Hmmm，I tested it on my own project and I seem to have lost the code indentation，

And it doesn't seem like there should be a specific suggestion bolck here.GPT just wants a clarification or explanation here.


Anyway, this feature is a big step forward for the Action. I'll continue to work on how to optimize these prompts when I have time. :)

![image](https://user-images.githubusercontent.com/38033263/230733285-fcf0fe40-3159-42e4-816e-75f084b66894.png)

**Comment by harjotgill** [comment]
Great! Try gpt-4 model if you have access to it. I don't see many formatting issues with that model.

**Comment by harjotgill** [comment]
This is implemented (more or less)
