### ISSUE TITLE
Adjust rules

### ISSUE THREAD

**Issue by pbjorklund** [fluxninja/openai-pr-reviewer#165]
I wonder if the prompt could be tuned in some way to pass in a list of rules that it does not need to validate. For instance it keeps complaining about missing comments when we are internally trying to do minimal commenting and instead focusing on readable code.

**Comment by pbjorklund** [comment]
Yeah, but I do like the idea of someone else keeping a good sane base-prompt up to date. Just having some form of "extra-instruction" param as a consumer would be neat.

**Comment by harjotgill** [comment]
Yes, we are constantly iterating the prompt. Programming in English is fun and unpredictable at the same time. Just keep sending feedback and will appreciate any pull requests that improve the base prompts! :)

**Comment by harjotgill** [comment]
This is fixed, I haven't seen a lot of review comments regarding missing comments lately.
