### ISSUE TITLE
Failed runs on deleted branches

### ISSUE THREAD

**Issue by ckcr4lyf** [fluxninja/openai-pr-reviewer#224]
Full disclosure: I was explicitly trying to trigger edge cases

I commented on a diff in an MR that was already  merged (and hence original branch deleted): https://github.com/fluxninja/openai-pr-reviewer/pull/218/files/362ff2b8e3614a38c5705426672bf9130bdd4b11#diff-6237e411e4b5750f5e3713c4739039620a279cdf9c8c596d573a97e87f1c8e0f

Seems the action tried to initiate a run to review the code based on my comment, but there is no branch, so it failed: https://github.com/fluxninja/openai-pr-reviewer/actions/runs/4762183914/jobs/8464139310#step:2:57

Just reporting a bug!

**Comment by harjotgill** [comment]
The `actions/checkout@v3` step fails, and there isn't much we can do about it. This action isn't even getting invoked. 
The GitHub event trigger doesn't contain sufficiently filter out this scenario. See PR review comment [trigger docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review_comment).
