### ISSUE TITLE
Getting plenty of "not found" errors

### ISSUE THREAD

**Issue by AsafMah** [fluxninja/openai-pr-reviewer#257]
Seems like the plugin fails to access about half the files

Here is a build example:
https://github.com/Azure/azure-kusto-java/actions/runs/4817214645/jobs/8577652848#step:2:152

**Comment by AsafMah** [comment]
Thank you, I'll close.

**Comment by darshilshahquantive** [comment]
@AsafMah have you used azure openai as openai_base_url?
i am trying to do it and getting this error :

```
 response: undefined, failed to send message to openai: Error: OpenAI error 404: {"error":{"code":"404","message": "Resource not found"}}, backtrace: Error: OpenAI error 404: {"error":{"code":"404","message": "Resource not found"}}
    at Promise.then.promptTokens (/actions-runner/_work/_actions/fluxninja/openai-pr-reviewer/latest/dist/index.js:3310:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```


and this is how my workflow yaml looks like :
`name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [ created ]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: self-hosted
    environment: new-env
    steps:
      - uses: fluxninja/openai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          openai_base_url: https://<deployment-name>.openai.azure.com/`

**Comment by AsafMah** [comment]
they have a much different api, you will need some sort of proxy.
