### ISSUE TITLE
API Secrets during a merge from fork

### ISSUE THREAD

**Issue by Fermain** [fluxninja/openai-pr-reviewer#74]
When a pull request is opened from a fork, the action does not create a bot successfully. It seems that this is because the API key, which is stored in the upstream repository secrets, is not available in the context of a PR from a fork. As a result, the action throws the following error message:

```
Warning: Skipped: failed to create bot, please check your openai_api_key: Error: Unable to initialize the OpenAI API, both 'OPENAI_API_KEY' environment variable are not available, backtrace: Error: Unable to initialize the OpenAI API, both 'OPENAI_API_KEY' environment variable are not available
```

### Steps to reproduce:

1. Set up the action in a repository, following the configuration instructions in the documentation.
2. Store the API key as a secret in the repository.
3. Create a fork of the repository.
4. Make changes in the fork and open a PR against the original repository.

### Expected behaviour:

Openai bot runs on pull requests regardless of origin.

### Actual behavior:

The action fails to create a bot on PRs opened from forks, as the API key stored in the repository secrets is not available.

**Comment by harjotgill** [comment]
Why should API key be shared with the forks?
The current behavior is expected behavior according to GitHub docs.

**Comment by Fermain** [comment]
My apologies, this is noted in the FAQ.
