### ISSUE TITLE
Sometimes what looks like an example review is passed through

### ISSUE THREAD

**Issue by elliots** [fluxninja/openai-pr-reviewer#76]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/622455/226818225-f0371d88-8073-43df-ac6f-1dc114ed9755.png">

Those files don't exist in the project or PR.

(Btw, brilliant work on this, we set it up this morning in our project and everyone is really liking it!)

**Comment by harjotgill** [comment]
You probably hit the OpenAI token limit. Try reducing the max number of files to process and add additional filters to exclude generated files etc.
